apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  labels:
    app: geth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
        - name: geth
          resources:
            requests:
              memory: "16G"
              cpu: "4000m"
            limits:
              memory: "128G"
              cpu: "8000m"
          image: docker pull ethereum/client-go
          command: ["geth"]
          args: [ "--http", "--http.addr=0.0.0.0", "--http.vhosts=geth-mainnet-full", "--http.api=eth,net,web3,txpool", "--ws", "--ws.addr=0.0.0.0", "--datadir=/data"]
          ports:
            - containerPort: 30303
            - containerPort: 8545
          volumeMounts:
          - mountPath: /data
            name: geth-volume
      volumes:
        - name: geth-volume
          persistentVolumeClaim:
            claimName: geth-claim