apiVersion: v1
kind: Service
metadata:
  name: geth-service
spec:
  type: NodePort
  selector:
    app: geth
  ports:
    - protocol: TCP
      name: ethtcp
      port: 30303
      targetPort: 30303
      nodePort: 30303
    - protocol: UDP
      name: ethudp
      port: 30303
      targetPort: 30303
      nodePort: 30303
    - protocol: TCP
      name: ethhttp
      port: 8545
      targetPort: 8545
      nodePort: 38545