name: Deploy Istio Gateway
on: workflow_dispatch
jobs:
  deploy-gateway:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/gateway
          kubectl apply -k kustomize
          kubectl -n istio-system patch svc istio-ingressgateway --type=json -p='[{"op": "add","path": "/spec/ports/-","value": {"name":"preview","nodePort":31432,"port":5432,"protocol":"TCP","targetPort":5432}}]' --dry-run=true -o yaml | kubectl apply -f -
          