name: 09 - Deploy Identity API
on:
  push:
    paths:
      - cluster/identity/oidc/**
jobs:
  deploy-identity-api:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/identity/oidc
          docker build . -t localhost:32000/oidc:latest
          docker push localhost:32000/oidc:latest
          kubectl apply -k kustomize
          kubectl delete pod -l app=oidc-postgres